### ISSUE TITLE
Why not system.numerics?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Leopotam/ecs-types#2]

**Comment by Leopotam** [comment]
`ecs-types` started for FW3.5 when no `system.numerics` classes were alive. About `system.numerics` - i think it was developed not for performance, but for compatibility / enterprise usage. Main goal of `ecs-types` - max performance instead of readability of code. Can you provide some tests where `system.numerics` faster than `ecs-types`? I will check and fix issues then.

**Comment by dzmitry-lahoda** [comment]
>  i think it was developed not for performance, but for compatibility / enterprise usage.
interesting to see such biased opinion, the case is advert - performance is the reason why system.numerics are part of .net.

**Comment by dzmitry-lahoda** [comment]
https://stackoverflow.com/questions/47446059/matrix3x2-performance

**Comment by dzmitry-lahoda** [comment]
I guess you may be interested in other endeavors made possible by new .net performance oriented stuff, like https://github.com/jtmueller/Collections.Pooled

**Comment by Leopotam** [comment]
> interesting to see such biased opinion, the case is advert - performance is the reason why system.numerics are part of .net.
So, I can just repeat myself:
>Can you provide some tests where `system.numerics` faster than `ecs-types`? I will check and fix issues then.

> https://stackoverflow.com/questions/47446059/matrix3x2-performance

And `ecs-types` will win in this test too even with multiplication due to use `in` modifier for struct parameters. Its still not ready for matrices, but `Float2`, `Float3`, `Float4`, `Int2`, `Int3` and `Int4` types are ready to use.

> I guess you may be interested in other endeavors made possible by new .net performance oriented stuff, like https://github.com/jtmueller/Collections.Pooled

I have no any interest in any collections due it just wrappers around arrays.

> Why not system.numerics?

Because I can? :)
